// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PetShop.Domain.Data.Context;

#nullable disable

namespace PetShop.Domain.Migrations
{
    [DbContext(typeof(PetShopDbContext))]
    [Migration("20220115132440_V5")]
    partial class V5
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("PetShop.Domain.Data.Models.Pet", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int>("Age")
                        .HasColumnType("int");

                    b.Property<string>("Breed")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Category")
                        .HasColumnType("int");

                    b.Property<string>("City")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("DateAdded")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Gender")
                        .HasColumnType("int");

                    b.Property<string>("ImageAddress")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Price")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Pets");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Age = 2,
                            Breed = "Husky",
                            Category = 1,
                            City = "Tehran",
                            DateAdded = new DateTime(2022, 1, 15, 16, 54, 40, 746, DateTimeKind.Local).AddTicks(1463),
                            Description = "Playful and Lazy at the same time!",
                            Gender = 0,
                            ImageAddress = "https://barkingroyalty.com/wp-content/uploads/2016/02/Alaskan-Malamutes.jpg",
                            IsActive = true,
                            Name = "Stanley",
                            Price = "100",
                            UserId = 1
                        },
                        new
                        {
                            Id = 2,
                            Age = 7,
                            Breed = "Catahoula Leopard",
                            Category = 1,
                            City = "Tehran",
                            DateAdded = new DateTime(2022, 1, 15, 16, 54, 40, 746, DateTimeKind.Local).AddTicks(1520),
                            Description = "A *Very* polite gentleman",
                            Gender = 0,
                            ImageAddress = "https://barkingroyalty.com/wp-content/uploads/2021/09/catahoula-leopard-dog.jpg",
                            IsActive = true,
                            Name = "Jackey",
                            Price = "0",
                            UserId = 1
                        },
                        new
                        {
                            Id = 3,
                            Age = 2,
                            Breed = "Domestic Medium-hair",
                            Category = 2,
                            City = "Pardis",
                            DateAdded = new DateTime(2022, 1, 15, 16, 54, 40, 746, DateTimeKind.Local).AddTicks(1531),
                            Description = "Snufkin is an affectionate, friendly lady who enjoys the quieter life (who doesn't?).",
                            Gender = 1,
                            ImageAddress = "https://www.battersea.org.uk/sites/default/files/animal_images/00P8e000001EdwGEAS.jpeg",
                            IsActive = true,
                            Name = "Snufkin",
                            Price = "2000",
                            UserId = 3
                        },
                        new
                        {
                            Id = 4,
                            Age = 2,
                            Breed = "Mastiff: Bull",
                            Category = 1,
                            City = "Shiraz",
                            DateAdded = new DateTime(2022, 1, 15, 16, 54, 40, 746, DateTimeKind.Local).AddTicks(1538),
                            Description = "Maisie is a young Bull breed full of energy and affection who is looking for a family who have experience with high energy dogs that require time, patience, and dedication towards their training. She is still developing and learning but has picked up some fantastic skills during her stay at Battersea Old Windsor. She has responded brilliantly to clicker training and this is being used to help her be a little calmer around other dogs.",
                            Gender = 1,
                            ImageAddress = "https://www.battersea.org.uk/sites/default/files/animal_images/00P8e000001EdbrEAC.jpeg",
                            IsActive = true,
                            Name = "Maisie",
                            Price = "2000",
                            UserId = 2
                        });
                });

            modelBuilder.Entity("PetShop.Domain.Data.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int>("Age")
                        .HasColumnType("int");

                    b.Property<string>("City")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Street")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Age = 23,
                            City = "Tehran",
                            Email = "mhkhk@outlook.com",
                            FirstName = "Mohammad Hassan",
                            IsActive = true,
                            LastName = "Khanipour",
                            Password = "123",
                            PhoneNumber = "09190777620",
                            Street = "Jeyhun"
                        },
                        new
                        {
                            Id = 2,
                            Age = 29,
                            City = "Shiraz",
                            Email = "h.kargar71@gmail.com",
                            FirstName = "Hossein",
                            IsActive = true,
                            LastName = "Kargar",
                            Password = "456",
                            PhoneNumber = "09357105475",
                            Street = "Shams"
                        },
                        new
                        {
                            Id = 3,
                            Age = 23,
                            City = "Pardis",
                            Email = "zeidimehran@gmail.com",
                            FirstName = "Mehran",
                            IsActive = true,
                            LastName = "Zeidi",
                            Password = "789",
                            PhoneNumber = "09386716209",
                            Street = "Mirzaee"
                        },
                        new
                        {
                            Id = 4,
                            Age = 22,
                            City = "Tehran",
                            Email = "mehdinaderi@gmail.com",
                            FirstName = "Mehdi",
                            IsActive = true,
                            LastName = "Naderi",
                            Password = "135",
                            PhoneNumber = "09225129985",
                            Street = "Piruzi"
                        });
                });

            modelBuilder.Entity("PetShop.Domain.Data.Models.Pet", b =>
                {
                    b.HasOne("PetShop.Domain.Data.Models.User", "User")
                        .WithMany("Pets")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("PetShop.Domain.Data.Models.User", b =>
                {
                    b.Navigation("Pets");
                });
#pragma warning restore 612, 618
        }
    }
}
